/*
 * Patient Evidence Api
 *
 * Patient Evidence and Prescription management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package project_evidence

import (
	"github.com/gin-gonic/gin"
)

type PatientEvidenceAPI interface {


    // CreateEvidedPatient Post /api/evidence/:ambulanceId/patients
    // Register a new patient 
     CreateEvidedPatient(c *gin.Context)

    // DeleteEvidedPatient Delete /api/evidence/:ambulanceId/patients/:patientId
    // Delete patient record 
     DeleteEvidedPatient(c *gin.Context)

    // GetEvidedPatient Get /api/evidence/:ambulanceId/patients/:patientId
    // Provides a single patient record 
     GetEvidedPatient(c *gin.Context)

    // GetEvidedPatients Get /api/evidence/:ambulanceId/patients
    // Provides the list of evidenced patients 
     GetEvidedPatients(c *gin.Context)

    // UpdateEvidedPatient Put /api/evidence/:ambulanceId/patients/:patientId
    // Update patient record 
     UpdateEvidedPatient(c *gin.Context)

}