/*
 * Patient Evidence Api
 *
 * Patient Evidence and Prescription management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package project_evidence

import (
	"github.com/gin-gonic/gin"
)

type PatientPrescriptionsAPI interface {


    // CreatePrescription Post /api/evidence/:ambulanceId/patients/:patientId/prescriptions
    // Create a new prescription 
     CreatePrescription(c *gin.Context)

    // DeletePrescription Delete /api/evidence/:ambulanceId/patients/:patientId/prescriptions/:prescriptionId
    // Delete prescription 
     DeletePrescription(c *gin.Context)

    // GetPatientPrescriptions Get /api/evidence/:ambulanceId/patients/:patientId/prescriptions
    // Provides the list of prescriptions for a patient 
     GetPatientPrescriptions(c *gin.Context)

    // GetPrescription Get /api/evidence/:ambulanceId/patients/:patientId/prescriptions/:prescriptionId
    // Provides a single prescription 
     GetPrescription(c *gin.Context)

    // UpdatePrescription Put /api/evidence/:ambulanceId/patients/:patientId/prescriptions/:prescriptionId
    // Update prescription 
     UpdatePrescription(c *gin.Context)

}