/*
 * Patient Evidence Api
 *
 * Patient Evidence and Prescription management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package project_evidence

type EvidedPatient struct {

	// Unique id of the patient record
	Id string `json:"id"`

	// Full name of the patient
	Name string `json:"name"`

	// Slovak national identification number
	RodneCislo string `json:"rodneCislo"`

	DateOfBirth string `json:"dateOfBirth"`

	Gender string `json:"gender"`

	Address string `json:"address,omitempty"`

	Phone string `json:"phone,omitempty"`

	Email string `json:"email,omitempty"`

	// Health insurance company
	Insurance string `json:"insurance"`

	BloodType string `json:"bloodType,omitempty"`

	// Free-text list of known allergies
	Allergies string `json:"allergies,omitempty"`

	// Free-text list of chronic conditions
	ChronicConditions string `json:"chronicConditions,omitempty"`

	// Free-text list of long-term medications
	Medications string `json:"medications,omitempty"`

	// List of prescriptions for this patient
	Prescriptions []Prescription `json:"prescriptions,omitempty"`
}
