/*
 * Patient Evidence Api
 *
 * Patient Evidence and Prescription management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package project_evidence

type Prescription struct {

	Id string `json:"id"`

	MedicineName string `json:"medicineName"`

	Strength string `json:"strength"`

	Form string `json:"form"`

	// Dosing schedule (morning-noon-evening-night)
	Dosage string `json:"dosage"`

	// Free-text patient instructions
	Instructions string `json:"instructions,omitempty"`

	Quantity string `json:"quantity"`

	// Anatomical Therapeutic Chemical classification code
	AtcCode string `json:"atcCode,omitempty"`

	PrescribedDate string `json:"prescribedDate"`

	ValidUntil string `json:"validUntil"`

	PrescribedBy string `json:"prescribedBy"`

	Status string `json:"status"`

	// Repeat prescription period in months (1 = single use)
	RepeatMonths int32 `json:"repeatMonths,omitempty"`

	// Insurance coverage level
	Coverage string `json:"coverage,omitempty"`
}
